begin;

create table if not exists public.admins (
  id integer generated by default as identity primary key,
  email text not null unique,
  name text not null,
  password_hash text not null,
  role text not null default 'owner'
);

create table if not exists public.categories (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order integer not null default 0
);

create table if not exists public.projects (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  location text not null,
  category_id integer references public.categories(id) on delete set null,
  summary text not null default '',
  description text not null default '',
  area_sqft integer,
  year integer,
  featured boolean not null default false,
  published boolean not null default false,
  sort_order integer not null default 0
);
create index if not exists projects_category_idx on public.projects(category_id);

create table if not exists public.project_images (
  id integer generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  base_path text not null,
  width integer not null,
  height integer not null,
  alt text not null default '',
  sort_order integer not null default 0,
  is_cover boolean not null default false
);
create index if not exists project_images_project_idx on public.project_images(project_id);

create table if not exists public.services (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  tagline text not null default '',
  description text not null default '',
  image_path text not null default '',
  visible boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.city_managers (
  id integer generated by default as identity primary key,
  name text not null,
  title text not null default 'City Manager',
  phone text not null default '',
  whatsapp text not null default '',
  email text not null default '',
  active boolean not null default true
);

create table if not exists public.cities (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  state text not null default '',
  enabled boolean not null default true,
  sort_order integer not null default 0,
  manager_id integer references public.city_managers(id) on delete set null,
  routing_whatsapp text not null default '',
  routing_email text not null default '',
  routing_notes text not null default ''
);

create table if not exists public.enquiries (
  id integer generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null default '',
  city_id integer references public.cities(id) on delete set null,
  city_name text not null,
  service_id integer references public.services(id) on delete set null,
  project_type text not null,
  budget text not null,
  preferred_date text not null,
  preferred_time text not null,
  meeting_type text not null,
  meeting_address text not null default '',
  message text not null default '',
  routed_manager_id integer references public.city_managers(id) on delete set null,
  routed_to text not null default '',
  status text not null default 'new',
  created_at text not null
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null
);

alter table public.admins enable row level security;
alter table public.categories enable row level security;
alter table public.projects enable row level security;
alter table public.project_images enable row level security;
alter table public.services enable row level security;
alter table public.city_managers enable row level security;
alter table public.cities enable row level security;
alter table public.enquiries enable row level security;
alter table public.site_settings enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'oakline-uploads',
  'oakline-uploads',
  true,
  15728640,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/heic', 'image/heif', 'image/tiff']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Oakline public image reads" on storage.objects;
create policy "Oakline public image reads"
on storage.objects for select
using (bucket_id = 'oakline-uploads');

commit;
